services:

  postgres:
    image: postgres:15
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_id
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  backend:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/windi_chat
      - JWT_SECRET_KEY=very_secret_key

    command: uvicorn app.main:app --host 0.0.0.0 --reload

volumes:
  postgres:
